# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gd3fni1uOPvhQ6LWwj7_aRgNZrk_WAKi
"""

!pip install streamlit
import streamlit as st
import time
import pandas as pd
import os

st.set_page_config(page_title="SOL Brand Quiz", page_icon="🎉", layout="centered")
st.title("🎉 Global Exhibition Day 2025 - SOL Brand Quiz")
st.markdown("Answer fast, earn more points! Each question has a 20-second timer. 🎯")

# Initialize session state for score and leaderboard
if 'score' not in st.session_state:
    st.session_state.score = 0
if 'current_q' not in st.session_state:
    st.session_state.current_q = 0
if 'leaderboard' not in st.session_state:
    st.session_state.leaderboard = []

# Questions format: (question, options, correct_answer, image_path or None)
questions = [
    ("Which brand’s booth is this?", ["Brand A", "Brand B", "Brand C", "Brand D"], "Brand B", "images/booth1.jpg"),
    ("What event was this setup part of?", ["CES", "GITEX", "IndiaWood", "Auto Expo"], "GITEX", "images/booth2.jpg"),
    ("Identify this CUH structure.", ["Ceiling only", "Upper Deck only", "CUH", "Only Hanging"], "CUH", "images/cuh_example.jpg")
]

q_index = st.session_state.current_q
if q_index < len(questions):
    q_text, options, correct_answer, image_path = questions[q_index]

    if image_path and os.path.exists(image_path):
        st.image(image_path, width=500)

    st.write(f"**Q{q_index + 1}: {q_text}**")

    start_time = time.time()
    user_answer = st.radio("Select your answer:", options, key=f"q_{q_index}")
    submit = st.button("Submit", key=f"submit_{q_index}")

    if submit:
        elapsed_time = time.time() - start_time
        time_bonus = max(0, 10 - int(elapsed_time // 2))  # Deduct 1 point every 2s

        if user_answer == correct_answer:
            st.success(f"Correct! You earned {time_bonus} points")
            st.session_state.score += time_bonus
        else:
            st.error("Incorrect!")

        st.session_state.leaderboard.append({
            'Q': q_index + 1,
            'Your Answer': user_answer,
            'Correct Answer': correct_answer,
            'Score This Q': time_bonus if user_answer == correct_answer else 0
        })

        st.session_state.current_q += 1
        st.experimental_rerun()
else:
    st.subheader("🎯 Final Results")
    st.write(f"**Your Final Score: {st.session_state.score} / {len(questions) * 10}**")

    leaderboard_df = pd.DataFrame(st.session_state.leaderboard)
    st.table(leaderboard_df)

    st.balloons()
    st.success("Thanks for playing the SOL Brand Quiz! 🥳")